name: flutter_markdown_editor
description: A package for markdown editor widget, you can use pre-exist editors or customize the view to build yours.
version: 1.1.1
homepage: https://github.com/ammaratef45/flutter_markdown_editor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown:
    git:
      url: https://github.com/apptreesoftware/flutter_markdown.git
  markdown:
    git:
      url: https://github.com/apptreesoftware/markdown.git
  url_launcher: ^5.7.2
  fluttertoast: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
